//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapR.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrapR.Models.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10,U,Pacific/Port_Moresby
        ///Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.7887,20,10,U,Pacific/Port_Moresby
        ///Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10,U,Pacific/Port_Moresby
        ///Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10,U,Pacific/Port_Moresby
        ///Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.22005,146,10,U,Pacific/Port_Moresby
        ///Wewak Intl,Wewak,P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string airports {
            get {
                return ResourceManager.GetString("airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba,AA,AW,U
        ///Antigua and Barbuda,AC,AG,U
        ///United Arab Emirates,AE,AE,U
        ///Afghanistan,AF,AF,U
        ///Algeria,AG,DZ,N
        ///Azerbaijan,AJ,AZ,E
        ///Albania,AL,AL,E
        ///Armenia,AM,AM,E
        ///Angola,AO,AO,N
        ///American Samoa,AQ,AS,U
        ///Argentina,AR,AR,S
        ///Australia,AS,AU,U
        ///Ashmore and Cartier Islands,AT,\N,\N
        ///Austria,AU,AT,E
        ///Anguilla,AV,AI,U
        ///Antarctica,AY,AQ,U
        ///Bahrain,BA,BH,U
        ///Barbados,BB,BB,U
        ///Botswana,BC,BW,U
        ///Bermuda,BD,BM,U
        ///Belgium,BE,BE,E
        ///Bahamas,BF,BS,U
        ///Bangladesh,BG,BD,U
        ///Belize,BH,BZ,U
        ///Bosnia and Herzegovina,BK,BA,E
        ///Bol [rest of string was truncated]&quot;;.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.4&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jQuery {
            get {
                return ResourceManager.GetString("jQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;object&quot;!=typeof JSON&amp;&amp;(JSON={}),function(){&quot;use strict&quot;;function f(a){return a&lt;10?&quot;0&quot;+a:a}function this_value(){return this.valueOf()}function quote(a){return rx_escapable.lastIndex=0,rx_escapable.test(a)?&apos;&quot;&apos;+a.replace(rx_escapable,function(a){var b=meta[a];return&quot;string&quot;==typeof b?b:&quot;\\u&quot;+(&quot;0000&quot;+a.charCodeAt(0).toString(16)).slice(-4)})+&apos;&quot;&apos;:&apos;&quot;&apos;+a+&apos;&quot;&apos;}function str(a,b){var c,d,e,f,h,g=gap,i=b[a];switch(i&amp;&amp;&quot;object&quot;==typeof i&amp;&amp;&quot;function&quot;==typeof i.toJSON&amp;&amp;(i=i.toJSON(a)),&quot;function&quot;==typeof rep&amp;&amp;(i=rep.call( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function camelize(a){return a.replace(/(?:^\w|[A-Z]|\b\w)/g,function(a,b){return 0==b?a.toLowerCase():a.toUpperCase()}).replace(/\s+/g,&quot;&quot;)}function setTripData(a,b){if(&quot;string&quot;==typeof a&amp;&amp;(a=JSON.parse(a)),$(&quot;#&quot;+b+&quot;TripStartAirport&quot;).val(a.departureAirportId),$(&quot;#&quot;+b+&quot;TripEndAirport&quot;).val(a.arrivalAirportId),$(&apos;[name=&quot;adult&quot;]&apos;).val(a.adult||1),a.children&amp;&amp;a.children&gt;0&amp;&amp;$(&apos;[name=&quot;children&quot;]&apos;).val(a.children),a.infant&amp;&amp;a.infant&gt;0&amp;&amp;$(&apos;[name=&quot;infant&quot;]&apos;).val(a.infant),$(&apos;[name=&quot;flightClass&quot;]&apos;).val((a.flightClass [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvBeta_setFlightsData {
            get {
                return ResourceManager.GetString("trvBeta_setFlightsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;defaultTripType&quot;:&quot;Return&quot;,&quot;defaultCabinClass&quot;:&quot;Y&quot;,&quot;isTrue&quot;:true,&quot;isReturnTrip&quot;:false,&quot;isMultiCity&quot;:true,&quot;minimumDate&quot;:&quot;2016-11-27&quot;,&quot;multiCity&quot;:{&quot;items&quot;:[{&quot;departureAirport&quot;:{&quot;display&quot;:&quot;ABV - Abuja International Airport - Gwagwa, Nigeria&quot;,&quot;airport&quot;:{&quot;country&quot;:&quot;Nigeria&quot;,&quot;code&quot;:&quot;ABV&quot;,&quot;city&quot;:&quot;Gwagwa&quot;,&quot;countryCode&quot;:&quot;NG&quot;,&quot;name&quot;:&quot;Abuja International Airport&quot;},&quot;airportOptions&quot;:[]},&quot;arrivalAirport&quot;:{&quot;display&quot;:&quot;ENU - Enugu Airport - Enugu, Nigeria&quot;,&quot;airport&quot;:{&quot;country&quot;:&quot;Nigeria&quot;,&quot;code&quot;:&quot;ENU&quot;,&quot;city&quot;:&quot;Enugu&quot;,&quot;country [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvFix_sampleMultiData {
            get {
                return ResourceManager.GetString("trvFix_sampleMultiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;defaultTripType&quot;:&quot;Return&quot;,&quot;defaultCabinClass&quot;:&quot;Y&quot;,&quot;isTrue&quot;:true,&quot;isReturnTrip&quot;:false,&quot;isMultiCity&quot;:false,&quot;minimumDate&quot;:&quot;2016-11-27&quot;,&quot;multiCity&quot;:{&quot;items&quot;:[{&quot;departureAirport&quot;:{&quot;display&quot;:&quot;ABV - Abuja International Airport - Gwagwa, Nigeria&quot;,&quot;airport&quot;:{&quot;country&quot;:&quot;Nigeria&quot;,&quot;code&quot;:&quot;ABV&quot;,&quot;city&quot;:&quot;Gwagwa&quot;,&quot;countryCode&quot;:&quot;NG&quot;,&quot;name&quot;:&quot;Abuja International Airport&quot;},&quot;airportOptions&quot;:[]},&quot;arrivalAirport&quot;:{&quot;display&quot;:&quot;ENU - Enugu Airport - Enugu, Nigeria&quot;,&quot;airport&quot;:{&quot;country&quot;:&quot;Nigeria&quot;,&quot;code&quot;:&quot;ENU&quot;,&quot;city&quot;:&quot;Enugu&quot;,&quot;countr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvFix_sampleOneWayData {
            get {
                return ResourceManager.GetString("trvFix_sampleOneWayData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;defaultTripType&quot;:&quot;Return&quot;,&quot;defaultCabinClass&quot;:&quot;Y&quot;,&quot;isTrue&quot;:true,&quot;isReturnTrip&quot;:true,&quot;isMultiCity&quot;:false,&quot;minimumDate&quot;:&quot;2016-11-27&quot;,&quot;multiCity&quot;:{&quot;items&quot;:[{&quot;departureAirport&quot;:{&quot;display&quot;:&quot;ABV - Abuja International Airport - Gwagwa, Nigeria&quot;,&quot;airport&quot;:{&quot;country&quot;:&quot;Nigeria&quot;,&quot;code&quot;:&quot;ABV&quot;,&quot;city&quot;:&quot;Gwagwa&quot;,&quot;countryCode&quot;:&quot;NG&quot;,&quot;name&quot;:&quot;Abuja International Airport&quot;},&quot;airportOptions&quot;:[]},&quot;arrivalAirport&quot;:{&quot;display&quot;:&quot;ENU - Enugu Airport - Enugu, Nigeria&quot;,&quot;airport&quot;:{&quot;country&quot;:&quot;Nigeria&quot;,&quot;code&quot;:&quot;ENU&quot;,&quot;city&quot;:&quot;Enugu&quot;,&quot;country [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvFix_sampleReturnData {
            get {
                return ResourceManager.GetString("trvFix_sampleReturnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function createSetTripType(){var a=angular.element(&apos;[data-ng-controller=&quot;FlightSearchFormCtrl as searchCtrl&quot;]&apos;).scope();a.searchCtrl.setTripType=function(b){this.tripType=b,this.currentTripType=b,this.isMultiCity=&quot;Circle&quot;==b,this.isReturnTrip=&quot;Return&quot;==b,a.$applyAsync()}}function copyObject(a,b){for(var c in b)if(a&amp;&amp;a.hasOwnProperty(c)){var d=typeof a[c];&quot;airport&quot;==c?a[c]=b[c]:&quot;string&quot;==d||&quot;number&quot;==d||&quot;boolean&quot;==d||&quot;date&quot;==d?a[c]=b[c]:&quot;object&quot;==d?copyObject(a[c],b[c]):Array.isArray(b[c])&amp;&amp;copyArray(a[c],b[ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvFix_setFlightsData {
            get {
                return ResourceManager.GetString("trvFix_setFlightsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;trips&quot;:[{&quot;airportOrigin&quot;:&quot;Lagos,Nigeria-Murtala Muhammed(LOS)&quot;,&quot;airportDestination&quot;:&quot;Abuja,Nigeria-Nnamdi Azikiwe Intl(ABV)&quot;,&quot;departureDate&quot;:&quot;Sat, 03 Dec 2016&quot;,&quot;departureTime&quot;:&quot;Anytime&quot;,&quot;returnDate&quot;:&quot;Tue, 06 Dec 2016&quot;,&quot;returnTime&quot;:&quot;Anytime&quot;},{&quot;airportOrigin&quot;:&quot;Abuja,Nigeria-Nnamdi Azikiwe Intl(ABV)&quot;,&quot;airportDestination&quot;:&quot;London,United Kingdom-Heathrow(LHR)&quot;,&quot;departureDate&quot;:&quot;Fri, 09 Dec 2016&quot;,&quot;departureTime&quot;:&quot;Anytime&quot;,&quot;returnDate&quot;:&quot;&quot;,&quot;returnTime&quot;:&quot;Anytime&quot;}],&quot;adults&quot;:1,&quot;children&quot;:0,&quot;infants&quot;:0,&quot;tripClass&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvPaddy_sampleInternational {
            get {
                return ResourceManager.GetString("trvPaddy_sampleInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;trips&quot;:[{&quot;airportOrigin&quot;:&quot;Lagos, NG - Murtala Muhammed (LOS)&quot;,&quot;airportDestination&quot;:&quot;Abuja, NG - Nnamdi Azikiwe Intl (ABV)&quot;,&quot;departureDate&quot;:&quot;Sat, 03 Dec 2016&quot;,&quot;departureTime&quot;:&quot;&quot;,&quot;returnDate&quot;:&quot;Tue, 06 Dec 2016&quot;,&quot;returnTime&quot;:&quot;&quot;},{&quot;airportOrigin&quot;:&quot;Abuja, NG - Nnamdi Azikiwe Intl (ABV)&quot;,&quot;airportDestination&quot;:&quot;London, GB - Heathrow (LHR)&quot;,&quot;departureDate&quot;:&quot;Fri, 09 Dec 2016&quot;,&quot;departureTime&quot;:null,&quot;returnDate&quot;:&quot;&quot;,&quot;returnTime&quot;:&quot;&quot;}],&quot;adults&quot;:1,&quot;children&quot;:0,&quot;infants&quot;:0,&quot;tripClass&quot;:&quot;all&quot;,&quot;tripType&quot;:&quot;multi&quot;}.
        /// </summary>
        public static string trvPaddy_sampleLocal {
            get {
                return ResourceManager.GetString("trvPaddy_sampleLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;tripType&quot;: &quot;multi&quot;, &quot;isNewSession&quot;: false, &quot;travellers&quot;: { &quot;adults&quot;: 2, &quot;children&quot;: 0, &quot;infants&quot;: 0 }, &quot;moreOptions&quot;: {}, &quot;itineraries&quot;: [{ &quot;id&quot;: &quot;4b032ad8-f84b-4f18-84a7-754e411c20ad&quot;, &quot;departDate&quot;: &quot;2016-11-28&quot;, &quot;returnDate&quot;: &quot;2016-11-30&quot;, &quot;$$hashKey&quot;: &quot;object:45&quot;, &quot;origin&quot;: { &quot;display&quot;: &quot;Lagos (LOS)&quot;, &quot;value&quot;: { &quot;airport&quot;: &quot;Murtala Muhammed International Airport&quot;, &quot;city&quot;: &quot;Lagos&quot;, &quot;code&quot;: &quot;LOS&quot;, &quot;country&quot;: &quot;Nigeria&quot;, &quot;countryIata&quot;: &quot;NG&quot;, &quot;iata&quot;: &quot;LOS&quot;, &quot;locationId&quot;: &quot;airport_LOS&quot;, &quot;type&quot;: &quot;airport&quot; }  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvStart_SampleData {
            get {
                return ResourceManager.GetString("trvStart_SampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function setFlightData(a){&quot;string&quot;==typeof a&amp;&amp;(a=JSON.parse(a));var b=angular.element($(&quot;.search-form__row&quot;)[0]).scope(),c=b.$parent.searchFormController;c.searchData.tripType=a.tripType;for(var d=0;d&lt;a.itineraries.length;d++)c.searchData.itineraries[d]||(c.addFlight(),b.$apply()),c.searchData.itineraries[d].departDate=a.itineraries[d].departDate,c.searchData.itineraries[d].returnDate=a.itineraries[d].returnDate,c.searchData.itineraries[d].destination=a.itineraries[d].destination,c.searchData.itineraries[d] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string trvStart_setFlightsData {
            get {
                return ResourceManager.GetString("trvStart_setFlightsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function getFlightsData() 
        ///{ 
        ///	return JSON.stringify(angular.element(\&quot;[ng-controller]\&quot;).scope().flightmodeldata); 
        ///}.
        /// </summary>
        public static string wkn_getFlightsData {
            get {
                return ResourceManager.GetString("wkn_getFlightsData", resourceCulture);
            }
        }
    }
}
